stages:
  - build
  - deployment
  - run
  - custom
  - tests

# Inclusion du fichier orchestrator du depôt kronos-v8/research-and-development/kronos/devops/deployment
include:
  - project: 'kronos-framework/devops/deployment'
    ref: master
    file: 'orchestrator.yml'
  - local: '.custom-gitlab-ci.yml'

# # # # # # # # # # # # #
# ----- VARIABLES ----- #
# # # # # # # # # # # # #
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == 'demo'
      # Variables definies dans l'interface Gitlab du projet
      variables:
        DEPLOYMENT_KEY: $DEMO_SSH_KEY
        DEPLOYMENT_USER: $DEMO_USER
        DEPLOYMENT_DOMAIN: $DEMO_DOMAIN
        DEPLOYMENT_ROOTPATH: /var/www/html/demos/$PROJECT_NAME
        DEPLOYMENT_DISTRIBUTION: $LINUX_DISTRIBUTION
        SUPERVISOR_TASK: $DEMO_SUPERVISOR
        ENV_NAME: demo
        URL: https://$PROJECT_NAME.agoravita.dev
        ROOT_PASSWORD: $DEMO_ROOT_PASSWORD

    - if: $CI_COMMIT_BRANCH == 'preprod'
      # Variables definies dans l'interface Gitlab du projet
      variables:
        DEPLOYMENT_KEY: $PREPROD_SSH_KEY
        DEPLOYMENT_USER: $PREPROD_USER
        DEPLOYMENT_DOMAIN: $PREPROD_DOMAIN
        DEPLOYMENT_ROOTPATH: /var/www/html/preprod-$PROJECT_NAME
        DEPLOYMENT_DISTRIBUTION: $LINUX_DISTRIBUTION
        SUPERVISOR_TASK: $PREPROD_SUPERVISOR
        ENV_NAME: preprod
        URL: $PREPROD_PROJECT_URL
        ROOT_PASSWORD: $PREPROD_ROOT_PASSWORD

    - if: $CI_COMMIT_BRANCH == 'master'
      # Variables definies dans l'interface Gitlab du projet
      variables:
        DEPLOYMENT_KEY: $PROD_SSH_KEY
        DEPLOYMENT_USER: $PROD_USER
        DEPLOYMENT_DOMAIN: $PROD_DOMAIN
        DEPLOYMENT_ROOTPATH: /var/www/html/$PROJECT_NAME
        DEPLOYMENT_DISTRIBUTION: $LINUX_DISTRIBUTION
        SUPERVISOR_TASK: $PROD_SUPERVISOR
        ENV_NAME: prod
        URL: $PROD_PROJECT_URL
        ROOT_PASSWORD: $PROD_ROOT_PASSWORD

# # # # # # # # # # # # #
# --- ENVIRONNEMENT --- #
# # # # # # # # # # # # #
 
build_back_end:
  extends:
    - .build_back_end

build_front_end:
  extends:
    - .build_front_end

deploy_back_end:
  extends:
    - .deploy_back_end

deploy_front_end:
  extends:
    - .deploy_front_end

run_server:
  extends:
    - .run_server

tests:
  extends:
    - .tests
